package Reika.Satisforestry.Miner;

import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.world.World;
import net.minecraftforge.common.util.ForgeDirection;

import Reika.DragonAPI.Instantiable.Data.BlockStruct.FilledBlockArray;
import Reika.Satisforestry.Blocks.BlockMinerMulti.MinerBlocks;
import Reika.Satisforestry.Registry.SFBlocks;

public class MinerStructure {

	public static ForgeDirection getStructureDirection(World world, int x, int y, int z) {
		for (int i = 2; i < 6; i++) {
			ForgeDirection dir = ForgeDirection.VALID_DIRECTIONS[i];
			FilledBlockArray arr = getMinerStructure(world, x, y, z, dir);
			if (arr.matchInWorld())
				return dir;
		}
		return null;
	}

	private static void setBlock(FilledBlockArray array, ForgeDirection dir, int dx, int dy, int dz, Block b) {
		setBlock(array, dir, dx, dy, dz, b, -1);
	}

	@SuppressWarnings("incomplete-switch")
	private static void setBlock(FilledBlockArray array, ForgeDirection dir, int dx, int dy, int dz, Block b, int meta) {
		switch(dir) {
			case WEST:
				dx = -dx;
				dz = -dz;
				break;
			case NORTH: {
				int temp = -dx;
				dx = dz;
				dz = temp;
				break;
			}
			case SOUTH: {
				int temp = dx;
				dx = -dz;
				dz = temp;
				break;
			}
		}
		array.setBlock(dx, dy, dz, b, meta);
	}

	//default dir is EAST
	private static FilledBlockArray getMinerStructure(World world, int x, int y, int z, ForgeDirection dir) {
		FilledBlockArray array = new FilledBlockArray(world);
		Block b = SFBlocks.MINERMULTI.getBlockInstance();
		int i = x-3;
		int j = y;
		int k = z-2;

		//world.setBlock(i + 3, j + 0, k + 2, SFBlocks.RESOURCENODE.getBlockInstance());

		setBlock(array, dir, i + 0, j + 0, k + 0, Blocks.air);
		setBlock(array, dir, i + 0, j + 0, k + 1, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 0, j + 0, k + 2, Blocks.air);
		setBlock(array, dir, i + 0, j + 0, k + 3, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 0, j + 0, k + 4, Blocks.air);
		setBlock(array, dir, i + 0, j + 1, k + 0, Blocks.air);
		setBlock(array, dir, i + 0, j + 1, k + 1, b, MinerBlocks.GRAY.ordinal());
		setBlock(array, dir, i + 0, j + 1, k + 2, Blocks.air);
		setBlock(array, dir, i + 0, j + 1, k + 3, b, MinerBlocks.GRAY.ordinal());
		setBlock(array, dir, i + 0, j + 1, k + 4, Blocks.air);
		setBlock(array, dir, i + 0, j + 2, k + 0, Blocks.air);
		setBlock(array, dir, i + 0, j + 2, k + 1, b, MinerBlocks.GRAY.ordinal());
		setBlock(array, dir, i + 0, j + 2, k + 2, b, MinerBlocks.GRAY.ordinal());
		setBlock(array, dir, i + 0, j + 2, k + 3, b, MinerBlocks.GRAY.ordinal());
		setBlock(array, dir, i + 0, j + 2, k + 4, Blocks.air);
		setBlock(array, dir, i + 0, j + 3, k + 0, Blocks.air);
		setBlock(array, dir, i + 0, j + 3, k + 1, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 0, j + 3, k + 2, Blocks.air);
		setBlock(array, dir, i + 0, j + 3, k + 3, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 0, j + 3, k + 4, Blocks.air);
		setBlock(array, dir, i + 0, j + 4, k + 0, Blocks.air);
		setBlock(array, dir, i + 0, j + 4, k + 1, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 0, j + 4, k + 2, Blocks.air);
		setBlock(array, dir, i + 0, j + 4, k + 3, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 0, j + 4, k + 4, Blocks.air);
		setBlock(array, dir, i + 0, j + 5, k + 0, Blocks.air);
		setBlock(array, dir, i + 0, j + 5, k + 1, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 0, j + 5, k + 2, Blocks.air);
		setBlock(array, dir, i + 0, j + 5, k + 3, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 0, j + 5, k + 4, Blocks.air);
		setBlock(array, dir, i + 0, j + 6, k + 0, Blocks.air);
		setBlock(array, dir, i + 0, j + 6, k + 1, b, MinerBlocks.GRAY.ordinal());
		setBlock(array, dir, i + 0, j + 6, k + 2, Blocks.air);
		setBlock(array, dir, i + 0, j + 6, k + 3, b, MinerBlocks.GRAY.ordinal());
		setBlock(array, dir, i + 0, j + 6, k + 4, Blocks.air);
		setBlock(array, dir, i + 0, j + 7, k + 0, Blocks.air);
		setBlock(array, dir, i + 0, j + 7, k + 1, Blocks.air);
		setBlock(array, dir, i + 0, j + 7, k + 2, Blocks.air);
		setBlock(array, dir, i + 0, j + 7, k + 3, Blocks.air);
		setBlock(array, dir, i + 0, j + 7, k + 4, Blocks.air);
		setBlock(array, dir, i + 0, j + 8, k + 0, Blocks.air);
		setBlock(array, dir, i + 0, j + 8, k + 1, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 0, j + 8, k + 2, Blocks.air);
		setBlock(array, dir, i + 0, j + 8, k + 3, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 0, j + 8, k + 4, Blocks.air);
		setBlock(array, dir, i + 0, j + 9, k + 0, Blocks.air);
		setBlock(array, dir, i + 0, j + 9, k + 1, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 0, j + 9, k + 2, Blocks.air);
		setBlock(array, dir, i + 0, j + 9, k + 3, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 0, j + 9, k + 4, Blocks.air);
		setBlock(array, dir, i + 0, j + 10, k + 0, Blocks.air);
		setBlock(array, dir, i + 0, j + 10, k + 1, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 0, j + 10, k + 2, Blocks.air);
		setBlock(array, dir, i + 0, j + 10, k + 3, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 0, j + 10, k + 4, Blocks.air);
		setBlock(array, dir, i + 0, j + 11, k + 0, Blocks.air);
		setBlock(array, dir, i + 0, j + 11, k + 1, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 0, j + 11, k + 2, Blocks.air);
		setBlock(array, dir, i + 0, j + 11, k + 3, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 0, j + 11, k + 4, Blocks.air);
		setBlock(array, dir, i + 0, j + 12, k + 0, Blocks.air);
		setBlock(array, dir, i + 0, j + 12, k + 1, Blocks.air);
		setBlock(array, dir, i + 0, j + 12, k + 2, Blocks.air);
		setBlock(array, dir, i + 0, j + 12, k + 3, Blocks.air);
		setBlock(array, dir, i + 0, j + 12, k + 4, Blocks.air);/*
		setBlock(array, dir, i + 0, j + 13, k + 0, Blocks.air);
		setBlock(array, dir, i + 0, j + 13, k + 1, Blocks.air);
		setBlock(array, dir, i + 0, j + 13, k + 2, Blocks.air);
		setBlock(array, dir, i + 0, j + 13, k + 3, Blocks.air);
		setBlock(array, dir, i + 0, j + 13, k + 4, Blocks.air);*/
		setBlock(array, dir, i + 1, j + 0, k + 0, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 1, j + 0, k + 1, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 1, j + 0, k + 2, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 1, j + 0, k + 3, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 1, j + 0, k + 4, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 1, j + 1, k + 0, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 1, j + 1, k + 1, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 1, j + 1, k + 2, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 1, j + 1, k + 3, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 1, j + 1, k + 4, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 1, j + 2, k + 0, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 1, j + 2, k + 1, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 1, j + 2, k + 2, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 1, j + 2, k + 3, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 1, j + 2, k + 4, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 1, j + 3, k + 0, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 1, j + 3, k + 1, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 1, j + 3, k + 2, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 1, j + 3, k + 3, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 1, j + 3, k + 4, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 1, j + 4, k + 0, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 1, j + 4, k + 1, Blocks.air);
		setBlock(array, dir, i + 1, j + 4, k + 2, Blocks.air);
		setBlock(array, dir, i + 1, j + 4, k + 3, Blocks.air);
		setBlock(array, dir, i + 1, j + 4, k + 4, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 1, j + 5, k + 0, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 1, j + 5, k + 1, Blocks.air);
		setBlock(array, dir, i + 1, j + 5, k + 2, Blocks.air);
		setBlock(array, dir, i + 1, j + 5, k + 3, Blocks.air);
		setBlock(array, dir, i + 1, j + 5, k + 4, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 1, j + 6, k + 0, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 1, j + 6, k + 1, b, MinerBlocks.GRAY.ordinal());
		setBlock(array, dir, i + 1, j + 6, k + 2, b, MinerBlocks.GRAY.ordinal());
		setBlock(array, dir, i + 1, j + 6, k + 3, b, MinerBlocks.GRAY.ordinal());
		setBlock(array, dir, i + 1, j + 6, k + 4, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 1, j + 7, k + 0, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 1, j + 7, k + 1, Blocks.air);
		setBlock(array, dir, i + 1, j + 7, k + 2, Blocks.air);
		setBlock(array, dir, i + 1, j + 7, k + 3, Blocks.air);
		setBlock(array, dir, i + 1, j + 7, k + 4, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 1, j + 8, k + 0, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 1, j + 8, k + 1, Blocks.air);
		setBlock(array, dir, i + 1, j + 8, k + 2, Blocks.air);
		setBlock(array, dir, i + 1, j + 8, k + 3, Blocks.air);
		setBlock(array, dir, i + 1, j + 8, k + 4, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 1, j + 9, k + 0, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 1, j + 9, k + 1, Blocks.air);
		setBlock(array, dir, i + 1, j + 9, k + 2, Blocks.air);
		setBlock(array, dir, i + 1, j + 9, k + 3, Blocks.air);
		setBlock(array, dir, i + 1, j + 9, k + 4, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 1, j + 10, k + 0, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 1, j + 10, k + 1, Blocks.air);
		setBlock(array, dir, i + 1, j + 10, k + 2, Blocks.air);
		setBlock(array, dir, i + 1, j + 10, k + 3, Blocks.air);
		setBlock(array, dir, i + 1, j + 10, k + 4, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 1, j + 11, k + 0, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 1, j + 11, k + 1, Blocks.air);
		setBlock(array, dir, i + 1, j + 11, k + 2, Blocks.air);
		setBlock(array, dir, i + 1, j + 11, k + 3, Blocks.air);
		setBlock(array, dir, i + 1, j + 11, k + 4, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 1, j + 12, k + 0, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 1, j + 12, k + 1, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 1, j + 12, k + 2, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 1, j + 12, k + 3, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 1, j + 12, k + 4, b, MinerBlocks.DARK.ordinal());/*
		setBlock(array, dir, i + 1, j + 13, k + 0, Blocks.air);
		setBlock(array, dir, i + 1, j + 13, k + 1, Blocks.air);
		setBlock(array, dir, i + 1, j + 13, k + 2, Blocks.air);
		setBlock(array, dir, i + 1, j + 13, k + 3, Blocks.air);
		setBlock(array, dir, i + 1, j + 13, k + 4, Blocks.air);*/
		setBlock(array, dir, i + 2, j + 0, k + 0, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 2, j + 0, k + 1, Blocks.air);
		setBlock(array, dir, i + 2, j + 0, k + 2, Blocks.air);
		setBlock(array, dir, i + 2, j + 0, k + 3, Blocks.air);
		setBlock(array, dir, i + 2, j + 0, k + 4, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 2, j + 1, k + 0, Blocks.air);
		setBlock(array, dir, i + 2, j + 1, k + 1, Blocks.air);
		setBlock(array, dir, i + 2, j + 1, k + 2, b, MinerBlocks.DRILL.ordinal());
		setBlock(array, dir, i + 2, j + 1, k + 3, Blocks.air);
		setBlock(array, dir, i + 2, j + 1, k + 4, Blocks.air);
		setBlock(array, dir, i + 2, j + 2, k + 0, Blocks.air);
		setBlock(array, dir, i + 2, j + 2, k + 1, Blocks.air);
		setBlock(array, dir, i + 2, j + 2, k + 2, b, MinerBlocks.DRILL.ordinal());
		setBlock(array, dir, i + 2, j + 2, k + 3, Blocks.air);
		setBlock(array, dir, i + 2, j + 2, k + 4, Blocks.air);
		setBlock(array, dir, i + 2, j + 3, k + 0, Blocks.air);
		setBlock(array, dir, i + 2, j + 3, k + 1, Blocks.air);
		setBlock(array, dir, i + 2, j + 3, k + 2, Blocks.air);
		setBlock(array, dir, i + 2, j + 3, k + 3, Blocks.air);
		setBlock(array, dir, i + 2, j + 3, k + 4, Blocks.air);
		setBlock(array, dir, i + 2, j + 4, k + 0, Blocks.air);
		setBlock(array, dir, i + 2, j + 4, k + 1, Blocks.air);
		setBlock(array, dir, i + 2, j + 4, k + 2, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 2, j + 4, k + 3, Blocks.air);
		setBlock(array, dir, i + 2, j + 4, k + 4, Blocks.air);
		setBlock(array, dir, i + 2, j + 5, k + 0, Blocks.air);
		setBlock(array, dir, i + 2, j + 5, k + 1, Blocks.air);
		setBlock(array, dir, i + 2, j + 5, k + 2, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 2, j + 5, k + 3, Blocks.air);
		setBlock(array, dir, i + 2, j + 5, k + 4, Blocks.air);
		setBlock(array, dir, i + 2, j + 6, k + 0, b, MinerBlocks.GRAY.ordinal());
		setBlock(array, dir, i + 2, j + 6, k + 1, Blocks.air);
		setBlock(array, dir, i + 2, j + 6, k + 2, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 2, j + 6, k + 3, Blocks.air);
		setBlock(array, dir, i + 2, j + 6, k + 4, b, MinerBlocks.GRAY.ordinal());
		setBlock(array, dir, i + 2, j + 7, k + 0, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 2, j + 7, k + 1, Blocks.air);
		setBlock(array, dir, i + 2, j + 7, k + 2, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 2, j + 7, k + 3, Blocks.air);
		setBlock(array, dir, i + 2, j + 7, k + 4, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 2, j + 8, k + 0, Blocks.air);
		setBlock(array, dir, i + 2, j + 8, k + 1, Blocks.air);
		setBlock(array, dir, i + 2, j + 8, k + 2, b, MinerBlocks.GRAY.ordinal());
		setBlock(array, dir, i + 2, j + 8, k + 3, Blocks.air);
		setBlock(array, dir, i + 2, j + 8, k + 4, Blocks.air);
		setBlock(array, dir, i + 2, j + 9, k + 0, Blocks.air);
		setBlock(array, dir, i + 2, j + 9, k + 1, Blocks.air);
		setBlock(array, dir, i + 2, j + 9, k + 2, b, MinerBlocks.GRAY.ordinal());
		setBlock(array, dir, i + 2, j + 9, k + 3, Blocks.air);
		setBlock(array, dir, i + 2, j + 9, k + 4, Blocks.air);
		setBlock(array, dir, i + 2, j + 10, k + 0, Blocks.air);
		setBlock(array, dir, i + 2, j + 10, k + 1, Blocks.air);
		setBlock(array, dir, i + 2, j + 10, k + 2, b, MinerBlocks.GRAY.ordinal());
		setBlock(array, dir, i + 2, j + 10, k + 3, Blocks.air);
		setBlock(array, dir, i + 2, j + 10, k + 4, Blocks.air);
		setBlock(array, dir, i + 2, j + 11, k + 0, Blocks.air);
		setBlock(array, dir, i + 2, j + 11, k + 1, Blocks.air);
		setBlock(array, dir, i + 2, j + 11, k + 2, b, MinerBlocks.GRAY.ordinal());
		setBlock(array, dir, i + 2, j + 11, k + 3, Blocks.air);
		setBlock(array, dir, i + 2, j + 11, k + 4, Blocks.air);
		setBlock(array, dir, i + 2, j + 12, k + 0, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 2, j + 12, k + 1, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 2, j + 12, k + 2, b, MinerBlocks.HUB.ordinal());
		setBlock(array, dir, i + 2, j + 12, k + 3, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 2, j + 12, k + 4, b, MinerBlocks.ORANGE.ordinal());/*
		setBlock(array, dir, i + 2, j + 13, k + 0, Blocks.air);
		setBlock(array, dir, i + 2, j + 13, k + 1, Blocks.air);
		setBlock(array, dir, i + 2, j + 13, k + 2, Blocks.air);
		setBlock(array, dir, i + 2, j + 13, k + 3, Blocks.air);
		setBlock(array, dir, i + 2, j + 13, k + 4, Blocks.air);*/
		setBlock(array, dir, i + 3, j + 0, k + 0, Blocks.air);
		setBlock(array, dir, i + 3, j + 0, k + 1, Blocks.air);
		setBlock(array, dir, i + 3, j + 0, k + 3, Blocks.air);
		setBlock(array, dir, i + 3, j + 0, k + 4, Blocks.air);
		setBlock(array, dir, i + 3, j + 1, k + 0, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 3, j + 1, k + 1, b, MinerBlocks.DRILL.ordinal());
		setBlock(array, dir, i + 3, j + 1, k + 2, b, MinerBlocks.DRILL.ordinal());
		setBlock(array, dir, i + 3, j + 1, k + 3, b, MinerBlocks.DRILL.ordinal());
		setBlock(array, dir, i + 3, j + 1, k + 4, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 3, j + 2, k + 0, Blocks.air);
		setBlock(array, dir, i + 3, j + 2, k + 1, b, MinerBlocks.DRILL.ordinal());
		setBlock(array, dir, i + 3, j + 2, k + 2, b, MinerBlocks.DRILL.ordinal());
		setBlock(array, dir, i + 3, j + 2, k + 3, b, MinerBlocks.DRILL.ordinal());
		setBlock(array, dir, i + 3, j + 2, k + 4, Blocks.air);
		setBlock(array, dir, i + 3, j + 3, k + 0, Blocks.air);
		setBlock(array, dir, i + 3, j + 3, k + 1, Blocks.air);
		setBlock(array, dir, i + 3, j + 3, k + 2, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 3, j + 3, k + 3, Blocks.air);
		setBlock(array, dir, i + 3, j + 3, k + 4, Blocks.air);
		setBlock(array, dir, i + 3, j + 4, k + 0, Blocks.air);
		setBlock(array, dir, i + 3, j + 4, k + 1, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 3, j + 4, k + 2, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 3, j + 4, k + 3, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 3, j + 4, k + 4, Blocks.air);
		setBlock(array, dir, i + 3, j + 5, k + 0, Blocks.air);
		setBlock(array, dir, i + 3, j + 5, k + 1, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 3, j + 5, k + 2, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 3, j + 5, k + 3, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 3, j + 5, k + 4, Blocks.air);
		setBlock(array, dir, i + 3, j + 6, k + 0, b, MinerBlocks.GRAY.ordinal());
		setBlock(array, dir, i + 3, j + 6, k + 1, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 3, j + 6, k + 2, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 3, j + 6, k + 3, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 3, j + 6, k + 4, b, MinerBlocks.GRAY.ordinal());
		setBlock(array, dir, i + 3, j + 7, k + 0, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 3, j + 7, k + 1, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 3, j + 7, k + 2, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 3, j + 7, k + 3, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 3, j + 7, k + 4, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 3, j + 8, k + 0, Blocks.air);
		setBlock(array, dir, i + 3, j + 8, k + 1, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 3, j + 8, k + 2, Blocks.air);
		setBlock(array, dir, i + 3, j + 8, k + 3, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 3, j + 8, k + 4, Blocks.air);
		setBlock(array, dir, i + 3, j + 9, k + 0, Blocks.air);
		setBlock(array, dir, i + 3, j + 9, k + 1, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 3, j + 9, k + 2, Blocks.air);
		setBlock(array, dir, i + 3, j + 9, k + 3, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 3, j + 9, k + 4, Blocks.air);
		setBlock(array, dir, i + 3, j + 10, k + 0, Blocks.air);
		setBlock(array, dir, i + 3, j + 10, k + 1, Blocks.air);
		setBlock(array, dir, i + 3, j + 10, k + 2, Blocks.air);
		setBlock(array, dir, i + 3, j + 10, k + 3, Blocks.air);
		setBlock(array, dir, i + 3, j + 10, k + 4, Blocks.air);
		setBlock(array, dir, i + 3, j + 11, k + 0, Blocks.air);
		setBlock(array, dir, i + 3, j + 11, k + 1, Blocks.air);
		setBlock(array, dir, i + 3, j + 11, k + 2, b, MinerBlocks.GRAY.ordinal());
		setBlock(array, dir, i + 3, j + 11, k + 3, Blocks.air);
		setBlock(array, dir, i + 3, j + 11, k + 4, Blocks.air);
		setBlock(array, dir, i + 3, j + 12, k + 0, Blocks.air);
		setBlock(array, dir, i + 3, j + 12, k + 1, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 3, j + 12, k + 2, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 3, j + 12, k + 3, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 3, j + 12, k + 4, b, MinerBlocks.POWER.ordinal());/*
		setBlock(array, dir, i + 3, j + 13, k + 0, Blocks.air);
		setBlock(array, dir, i + 3, j + 13, k + 1, Blocks.air);
		setBlock(array, dir, i + 3, j + 13, k + 2, Blocks.air);
		setBlock(array, dir, i + 3, j + 13, k + 3, Blocks.air);*/
		setBlock(array, dir, i + 3, j + 13, k + 4, b, MinerBlocks.POWER.ordinal());
		setBlock(array, dir, i + 4, j + 0, k + 0, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 4, j + 0, k + 1, Blocks.air);
		setBlock(array, dir, i + 4, j + 0, k + 2, Blocks.air);
		setBlock(array, dir, i + 4, j + 0, k + 3, Blocks.air);
		setBlock(array, dir, i + 4, j + 0, k + 4, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 4, j + 1, k + 0, Blocks.air);
		setBlock(array, dir, i + 4, j + 1, k + 1, Blocks.air);
		setBlock(array, dir, i + 4, j + 1, k + 2, b, MinerBlocks.DRILL.ordinal());
		setBlock(array, dir, i + 4, j + 1, k + 3, Blocks.air);
		setBlock(array, dir, i + 4, j + 1, k + 4, Blocks.air);
		setBlock(array, dir, i + 4, j + 2, k + 0, Blocks.air);
		setBlock(array, dir, i + 4, j + 2, k + 1, Blocks.air);
		setBlock(array, dir, i + 4, j + 2, k + 2, b, MinerBlocks.DRILL.ordinal());
		setBlock(array, dir, i + 4, j + 2, k + 3, Blocks.air);
		setBlock(array, dir, i + 4, j + 2, k + 4, Blocks.air);
		setBlock(array, dir, i + 4, j + 3, k + 0, Blocks.air);
		setBlock(array, dir, i + 4, j + 3, k + 1, Blocks.air);
		setBlock(array, dir, i + 4, j + 3, k + 2, Blocks.air);
		setBlock(array, dir, i + 4, j + 3, k + 3, Blocks.air);
		setBlock(array, dir, i + 4, j + 3, k + 4, Blocks.air);
		setBlock(array, dir, i + 4, j + 4, k + 0, Blocks.air);
		setBlock(array, dir, i + 4, j + 4, k + 1, Blocks.air);
		setBlock(array, dir, i + 4, j + 4, k + 2, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 4, j + 4, k + 3, Blocks.air);
		setBlock(array, dir, i + 4, j + 4, k + 4, Blocks.air);
		setBlock(array, dir, i + 4, j + 5, k + 0, Blocks.air);
		setBlock(array, dir, i + 4, j + 5, k + 1, Blocks.air);
		setBlock(array, dir, i + 4, j + 5, k + 2, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 4, j + 5, k + 3, Blocks.air);
		setBlock(array, dir, i + 4, j + 5, k + 4, Blocks.air);
		setBlock(array, dir, i + 4, j + 6, k + 0, b, MinerBlocks.GRAY.ordinal());
		setBlock(array, dir, i + 4, j + 6, k + 1, Blocks.air);
		setBlock(array, dir, i + 4, j + 6, k + 2, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 4, j + 6, k + 3, Blocks.air);
		setBlock(array, dir, i + 4, j + 6, k + 4, b, MinerBlocks.GRAY.ordinal());
		setBlock(array, dir, i + 4, j + 7, k + 0, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 4, j + 7, k + 1, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 4, j + 7, k + 2, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 4, j + 7, k + 3, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 4, j + 7, k + 4, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 4, j + 8, k + 0, Blocks.air);
		setBlock(array, dir, i + 4, j + 8, k + 1, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 4, j + 8, k + 2, b, MinerBlocks.GRAY.ordinal());
		setBlock(array, dir, i + 4, j + 8, k + 3, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 4, j + 8, k + 4, Blocks.air);
		setBlock(array, dir, i + 4, j + 9, k + 0, Blocks.air);
		setBlock(array, dir, i + 4, j + 9, k + 1, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 4, j + 9, k + 2, b, MinerBlocks.GRAY.ordinal());
		setBlock(array, dir, i + 4, j + 9, k + 3, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 4, j + 9, k + 4, Blocks.air);
		setBlock(array, dir, i + 4, j + 10, k + 0, Blocks.air);
		setBlock(array, dir, i + 4, j + 10, k + 1, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 4, j + 10, k + 2, b, MinerBlocks.GRAY.ordinal());
		setBlock(array, dir, i + 4, j + 10, k + 3, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 4, j + 10, k + 4, Blocks.air);
		setBlock(array, dir, i + 4, j + 11, k + 0, Blocks.air);
		setBlock(array, dir, i + 4, j + 11, k + 1, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 4, j + 11, k + 2, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 4, j + 11, k + 3, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 4, j + 11, k + 4, Blocks.air);
		setBlock(array, dir, i + 4, j + 12, k + 0, Blocks.air);
		setBlock(array, dir, i + 4, j + 12, k + 1, Blocks.air);
		setBlock(array, dir, i + 4, j + 12, k + 2, Blocks.air);
		setBlock(array, dir, i + 4, j + 12, k + 3, Blocks.air);
		setBlock(array, dir, i + 4, j + 12, k + 4, Blocks.air);/*
		setBlock(array, dir, i + 4, j + 13, k + 0, Blocks.air);
		setBlock(array, dir, i + 4, j + 13, k + 1, Blocks.air);
		setBlock(array, dir, i + 4, j + 13, k + 2, Blocks.air);
		setBlock(array, dir, i + 4, j + 13, k + 3, Blocks.air);
		setBlock(array, dir, i + 4, j + 13, k + 4, Blocks.air);*/
		setBlock(array, dir, i + 5, j + 0, k + 0, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 5, j + 0, k + 1, Blocks.air);
		setBlock(array, dir, i + 5, j + 0, k + 2, Blocks.air);
		setBlock(array, dir, i + 5, j + 0, k + 3, Blocks.air);
		setBlock(array, dir, i + 5, j + 0, k + 4, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 5, j + 1, k + 0, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 5, j + 1, k + 1, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 5, j + 1, k + 2, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 5, j + 1, k + 3, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 5, j + 1, k + 4, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 5, j + 2, k + 0, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 5, j + 2, k + 1, Blocks.air);
		setBlock(array, dir, i + 5, j + 2, k + 2, Blocks.air);
		setBlock(array, dir, i + 5, j + 2, k + 3, Blocks.air);
		setBlock(array, dir, i + 5, j + 2, k + 4, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 5, j + 3, k + 0, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 5, j + 3, k + 1, Blocks.air);
		setBlock(array, dir, i + 5, j + 3, k + 2, Blocks.air);
		setBlock(array, dir, i + 5, j + 3, k + 3, Blocks.air);
		setBlock(array, dir, i + 5, j + 3, k + 4, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 5, j + 4, k + 0, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 5, j + 4, k + 1, Blocks.air);
		setBlock(array, dir, i + 5, j + 4, k + 2, Blocks.air);
		setBlock(array, dir, i + 5, j + 4, k + 3, Blocks.air);
		setBlock(array, dir, i + 5, j + 4, k + 4, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 5, j + 5, k + 0, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 5, j + 5, k + 1, Blocks.air);
		setBlock(array, dir, i + 5, j + 5, k + 2, Blocks.air);
		setBlock(array, dir, i + 5, j + 5, k + 3, Blocks.air);
		setBlock(array, dir, i + 5, j + 5, k + 4, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 5, j + 6, k + 0, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 5, j + 6, k + 1, b, MinerBlocks.GRAY.ordinal());
		setBlock(array, dir, i + 5, j + 6, k + 2, b, MinerBlocks.GRAY.ordinal());
		setBlock(array, dir, i + 5, j + 6, k + 3, b, MinerBlocks.GRAY.ordinal());
		setBlock(array, dir, i + 5, j + 6, k + 4, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 5, j + 7, k + 0, Blocks.air);
		setBlock(array, dir, i + 5, j + 7, k + 1, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 5, j + 7, k + 2, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 5, j + 7, k + 3, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 5, j + 7, k + 4, Blocks.air);
		setBlock(array, dir, i + 5, j + 8, k + 0, Blocks.air);
		setBlock(array, dir, i + 5, j + 8, k + 1, Blocks.air);
		setBlock(array, dir, i + 5, j + 8, k + 2, Blocks.air);
		setBlock(array, dir, i + 5, j + 8, k + 3, Blocks.air);
		setBlock(array, dir, i + 5, j + 8, k + 4, Blocks.air);
		setBlock(array, dir, i + 5, j + 9, k + 0, Blocks.air);
		setBlock(array, dir, i + 5, j + 9, k + 1, Blocks.air);
		setBlock(array, dir, i + 5, j + 9, k + 2, Blocks.air);
		setBlock(array, dir, i + 5, j + 9, k + 3, Blocks.air);
		setBlock(array, dir, i + 5, j + 9, k + 4, Blocks.air);
		setBlock(array, dir, i + 5, j + 10, k + 0, Blocks.air);
		setBlock(array, dir, i + 5, j + 10, k + 1, Blocks.air);
		setBlock(array, dir, i + 5, j + 10, k + 2, Blocks.air);
		setBlock(array, dir, i + 5, j + 10, k + 3, Blocks.air);
		setBlock(array, dir, i + 5, j + 10, k + 4, Blocks.air);
		setBlock(array, dir, i + 5, j + 11, k + 0, Blocks.air);
		setBlock(array, dir, i + 5, j + 11, k + 1, Blocks.air);
		setBlock(array, dir, i + 5, j + 11, k + 2, Blocks.air);
		setBlock(array, dir, i + 5, j + 11, k + 3, Blocks.air);
		setBlock(array, dir, i + 5, j + 11, k + 4, Blocks.air);
		setBlock(array, dir, i + 5, j + 12, k + 0, Blocks.air);
		setBlock(array, dir, i + 5, j + 12, k + 1, Blocks.air);
		setBlock(array, dir, i + 5, j + 12, k + 2, Blocks.air);
		setBlock(array, dir, i + 5, j + 12, k + 3, Blocks.air);
		setBlock(array, dir, i + 5, j + 12, k + 4, Blocks.air);/*
		setBlock(array, dir, i + 5, j + 13, k + 0, Blocks.air);
		setBlock(array, dir, i + 5, j + 13, k + 1, Blocks.air);
		setBlock(array, dir, i + 5, j + 13, k + 2, Blocks.air);
		setBlock(array, dir, i + 5, j + 13, k + 3, Blocks.air);
		setBlock(array, dir, i + 5, j + 13, k + 4, Blocks.air);*/
		setBlock(array, dir, i + 6, j + 0, k + 0, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 6, j + 0, k + 1, Blocks.air);
		setBlock(array, dir, i + 6, j + 0, k + 2, Blocks.air);
		setBlock(array, dir, i + 6, j + 0, k + 3, Blocks.air);
		setBlock(array, dir, i + 6, j + 0, k + 4, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 6, j + 1, k + 0, Blocks.air);
		setBlock(array, dir, i + 6, j + 1, k + 1, b, MinerBlocks.GRAY.ordinal());
		setBlock(array, dir, i + 6, j + 1, k + 2, b, MinerBlocks.GRAY.ordinal());
		setBlock(array, dir, i + 6, j + 1, k + 3, b, MinerBlocks.GRAY.ordinal());
		setBlock(array, dir, i + 6, j + 1, k + 4, Blocks.air);
		setBlock(array, dir, i + 6, j + 2, k + 0, Blocks.air);
		setBlock(array, dir, i + 6, j + 2, k + 1, Blocks.air);
		setBlock(array, dir, i + 6, j + 2, k + 2, Blocks.air);
		setBlock(array, dir, i + 6, j + 2, k + 3, Blocks.air);
		setBlock(array, dir, i + 6, j + 2, k + 4, Blocks.air);
		setBlock(array, dir, i + 6, j + 3, k + 0, Blocks.air);
		setBlock(array, dir, i + 6, j + 3, k + 1, Blocks.air);
		setBlock(array, dir, i + 6, j + 3, k + 2, Blocks.air);
		setBlock(array, dir, i + 6, j + 3, k + 3, Blocks.air);
		setBlock(array, dir, i + 6, j + 3, k + 4, Blocks.air);
		setBlock(array, dir, i + 6, j + 4, k + 0, Blocks.air);
		setBlock(array, dir, i + 6, j + 4, k + 1, Blocks.air);
		setBlock(array, dir, i + 6, j + 4, k + 2, Blocks.air);
		setBlock(array, dir, i + 6, j + 4, k + 3, Blocks.air);
		setBlock(array, dir, i + 6, j + 4, k + 4, Blocks.air);
		setBlock(array, dir, i + 6, j + 5, k + 0, Blocks.air);
		setBlock(array, dir, i + 6, j + 5, k + 1, Blocks.air);
		setBlock(array, dir, i + 6, j + 5, k + 2, Blocks.air);
		setBlock(array, dir, i + 6, j + 5, k + 3, Blocks.air);
		setBlock(array, dir, i + 6, j + 5, k + 4, Blocks.air);
		setBlock(array, dir, i + 6, j + 6, k + 0, Blocks.air);
		setBlock(array, dir, i + 6, j + 6, k + 1, Blocks.air);
		setBlock(array, dir, i + 6, j + 6, k + 2, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 6, j + 6, k + 3, Blocks.air);
		setBlock(array, dir, i + 6, j + 6, k + 4, Blocks.air);
		setBlock(array, dir, i + 6, j + 7, k + 0, Blocks.air);
		setBlock(array, dir, i + 6, j + 7, k + 1, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 6, j + 7, k + 2, Blocks.air);
		setBlock(array, dir, i + 6, j + 7, k + 3, Blocks.air);
		setBlock(array, dir, i + 6, j + 7, k + 4, Blocks.air);
		setBlock(array, dir, i + 6, j + 8, k + 0, Blocks.air);
		setBlock(array, dir, i + 6, j + 8, k + 1, Blocks.air);
		setBlock(array, dir, i + 6, j + 8, k + 2, Blocks.air);
		setBlock(array, dir, i + 6, j + 8, k + 3, Blocks.air);
		setBlock(array, dir, i + 6, j + 8, k + 4, Blocks.air);
		setBlock(array, dir, i + 6, j + 9, k + 0, Blocks.air);
		setBlock(array, dir, i + 6, j + 9, k + 1, Blocks.air);
		setBlock(array, dir, i + 6, j + 9, k + 2, Blocks.air);
		setBlock(array, dir, i + 6, j + 9, k + 3, Blocks.air);
		setBlock(array, dir, i + 6, j + 9, k + 4, Blocks.air);
		setBlock(array, dir, i + 6, j + 10, k + 0, Blocks.air);
		setBlock(array, dir, i + 6, j + 10, k + 1, Blocks.air);
		setBlock(array, dir, i + 6, j + 10, k + 2, Blocks.air);
		setBlock(array, dir, i + 6, j + 10, k + 3, Blocks.air);
		setBlock(array, dir, i + 6, j + 10, k + 4, Blocks.air);
		setBlock(array, dir, i + 6, j + 11, k + 0, Blocks.air);
		setBlock(array, dir, i + 6, j + 11, k + 1, Blocks.air);
		setBlock(array, dir, i + 6, j + 11, k + 2, Blocks.air);
		setBlock(array, dir, i + 6, j + 11, k + 3, Blocks.air);
		setBlock(array, dir, i + 6, j + 11, k + 4, Blocks.air);
		setBlock(array, dir, i + 6, j + 12, k + 0, Blocks.air);
		setBlock(array, dir, i + 6, j + 12, k + 1, Blocks.air);
		setBlock(array, dir, i + 6, j + 12, k + 2, Blocks.air);
		setBlock(array, dir, i + 6, j + 12, k + 3, Blocks.air);
		setBlock(array, dir, i + 6, j + 12, k + 4, Blocks.air);/*
		setBlock(array, dir, i + 6, j + 13, k + 0, Blocks.air);
		setBlock(array, dir, i + 6, j + 13, k + 1, Blocks.air);
		setBlock(array, dir, i + 6, j + 13, k + 2, Blocks.air);
		setBlock(array, dir, i + 6, j + 13, k + 3, Blocks.air);
		setBlock(array, dir, i + 6, j + 13, k + 4, Blocks.air);*/
		setBlock(array, dir, i + 7, j + 0, k + 0, Blocks.air);
		setBlock(array, dir, i + 7, j + 0, k + 1, Blocks.air);
		setBlock(array, dir, i + 7, j + 0, k + 2, Blocks.air);
		setBlock(array, dir, i + 7, j + 0, k + 3, Blocks.air);
		setBlock(array, dir, i + 7, j + 0, k + 4, Blocks.air);
		setBlock(array, dir, i + 7, j + 1, k + 0, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 7, j + 1, k + 1, Blocks.air);
		setBlock(array, dir, i + 7, j + 1, k + 2, Blocks.air);
		setBlock(array, dir, i + 7, j + 1, k + 3, Blocks.air);
		setBlock(array, dir, i + 7, j + 1, k + 4, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 7, j + 2, k + 0, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 7, j + 2, k + 1, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 7, j + 2, k + 2, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 7, j + 2, k + 3, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 7, j + 2, k + 4, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 7, j + 3, k + 0, Blocks.air);
		setBlock(array, dir, i + 7, j + 3, k + 1, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 7, j + 3, k + 2, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 7, j + 3, k + 3, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 7, j + 3, k + 4, Blocks.air);
		setBlock(array, dir, i + 7, j + 4, k + 0, Blocks.air);
		setBlock(array, dir, i + 7, j + 4, k + 1, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 7, j + 4, k + 2, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 7, j + 4, k + 3, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 7, j + 4, k + 4, Blocks.air);
		setBlock(array, dir, i + 7, j + 5, k + 0, Blocks.air);
		setBlock(array, dir, i + 7, j + 5, k + 1, Blocks.air);
		setBlock(array, dir, i + 7, j + 5, k + 2, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 7, j + 5, k + 3, Blocks.air);
		setBlock(array, dir, i + 7, j + 5, k + 4, Blocks.air);
		setBlock(array, dir, i + 7, j + 6, k + 0, Blocks.air);
		setBlock(array, dir, i + 7, j + 6, k + 1, Blocks.air);
		setBlock(array, dir, i + 7, j + 6, k + 2, Blocks.air);
		setBlock(array, dir, i + 7, j + 6, k + 3, Blocks.air);
		setBlock(array, dir, i + 7, j + 6, k + 4, Blocks.air);
		setBlock(array, dir, i + 7, j + 7, k + 0, Blocks.air);
		setBlock(array, dir, i + 7, j + 7, k + 1, Blocks.air);
		setBlock(array, dir, i + 7, j + 7, k + 2, Blocks.air);
		setBlock(array, dir, i + 7, j + 7, k + 3, Blocks.air);
		setBlock(array, dir, i + 7, j + 7, k + 4, Blocks.air);
		setBlock(array, dir, i + 7, j + 8, k + 0, Blocks.air);
		setBlock(array, dir, i + 7, j + 8, k + 1, Blocks.air);
		setBlock(array, dir, i + 7, j + 8, k + 2, Blocks.air);
		setBlock(array, dir, i + 7, j + 8, k + 3, Blocks.air);
		setBlock(array, dir, i + 7, j + 8, k + 4, Blocks.air);
		setBlock(array, dir, i + 7, j + 9, k + 0, Blocks.air);
		setBlock(array, dir, i + 7, j + 9, k + 1, Blocks.air);
		setBlock(array, dir, i + 7, j + 9, k + 2, Blocks.air);
		setBlock(array, dir, i + 7, j + 9, k + 3, Blocks.air);
		setBlock(array, dir, i + 7, j + 9, k + 4, Blocks.air);
		setBlock(array, dir, i + 7, j + 10, k + 0, Blocks.air);
		setBlock(array, dir, i + 7, j + 10, k + 1, Blocks.air);
		setBlock(array, dir, i + 7, j + 10, k + 2, Blocks.air);
		setBlock(array, dir, i + 7, j + 10, k + 3, Blocks.air);
		setBlock(array, dir, i + 7, j + 10, k + 4, Blocks.air);
		setBlock(array, dir, i + 7, j + 11, k + 0, Blocks.air);
		setBlock(array, dir, i + 7, j + 11, k + 1, Blocks.air);
		setBlock(array, dir, i + 7, j + 11, k + 2, Blocks.air);
		setBlock(array, dir, i + 7, j + 11, k + 3, Blocks.air);
		setBlock(array, dir, i + 7, j + 11, k + 4, Blocks.air);
		setBlock(array, dir, i + 7, j + 12, k + 0, Blocks.air);
		setBlock(array, dir, i + 7, j + 12, k + 1, Blocks.air);
		setBlock(array, dir, i + 7, j + 12, k + 2, Blocks.air);
		setBlock(array, dir, i + 7, j + 12, k + 3, Blocks.air);
		setBlock(array, dir, i + 7, j + 12, k + 4, Blocks.air);/*
		setBlock(array, dir, i + 7, j + 13, k + 0, Blocks.air);
		setBlock(array, dir, i + 7, j + 13, k + 1, Blocks.air);
		setBlock(array, dir, i + 7, j + 13, k + 2, Blocks.air);
		setBlock(array, dir, i + 7, j + 13, k + 3, Blocks.air);
		setBlock(array, dir, i + 7, j + 13, k + 4, Blocks.air);*/
		setBlock(array, dir, i + 8, j + 0, k + 0, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 8, j + 0, k + 1, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 8, j + 0, k + 2, Blocks.air);
		setBlock(array, dir, i + 8, j + 0, k + 3, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 8, j + 0, k + 4, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 8, j + 1, k + 0, Blocks.air);
		setBlock(array, dir, i + 8, j + 1, k + 1, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 8, j + 1, k + 2, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 8, j + 1, k + 3, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 8, j + 1, k + 4, Blocks.air);
		setBlock(array, dir, i + 8, j + 2, k + 0, Blocks.air);
		setBlock(array, dir, i + 8, j + 2, k + 1, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 8, j + 2, k + 2, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 8, j + 2, k + 3, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 8, j + 2, k + 4, Blocks.air);
		setBlock(array, dir, i + 8, j + 3, k + 0, Blocks.air);
		setBlock(array, dir, i + 8, j + 3, k + 1, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 8, j + 3, k + 2, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 8, j + 3, k + 3, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 8, j + 3, k + 4, Blocks.air);
		setBlock(array, dir, i + 8, j + 4, k + 0, Blocks.air);
		setBlock(array, dir, i + 8, j + 4, k + 1, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 8, j + 4, k + 2, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 8, j + 4, k + 3, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 8, j + 4, k + 4, Blocks.air);
		setBlock(array, dir, i + 8, j + 5, k + 0, Blocks.air);
		setBlock(array, dir, i + 8, j + 5, k + 1, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 8, j + 5, k + 2, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 8, j + 5, k + 3, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 8, j + 5, k + 4, Blocks.air);
		setBlock(array, dir, i + 8, j + 6, k + 0, Blocks.air);
		setBlock(array, dir, i + 8, j + 6, k + 1, Blocks.air);
		setBlock(array, dir, i + 8, j + 6, k + 2, Blocks.air);
		setBlock(array, dir, i + 8, j + 6, k + 3, Blocks.air);
		setBlock(array, dir, i + 8, j + 6, k + 4, Blocks.air);
		setBlock(array, dir, i + 8, j + 7, k + 0, Blocks.air);
		setBlock(array, dir, i + 8, j + 7, k + 1, Blocks.air);
		setBlock(array, dir, i + 8, j + 7, k + 2, Blocks.air);
		setBlock(array, dir, i + 8, j + 7, k + 3, Blocks.air);
		setBlock(array, dir, i + 8, j + 7, k + 4, Blocks.air);
		setBlock(array, dir, i + 8, j + 8, k + 0, Blocks.air);
		setBlock(array, dir, i + 8, j + 8, k + 1, Blocks.air);
		setBlock(array, dir, i + 8, j + 8, k + 2, Blocks.air);
		setBlock(array, dir, i + 8, j + 8, k + 3, Blocks.air);
		setBlock(array, dir, i + 8, j + 8, k + 4, Blocks.air);
		setBlock(array, dir, i + 8, j + 9, k + 0, Blocks.air);
		setBlock(array, dir, i + 8, j + 9, k + 1, Blocks.air);
		setBlock(array, dir, i + 8, j + 9, k + 2, Blocks.air);
		setBlock(array, dir, i + 8, j + 9, k + 3, Blocks.air);
		setBlock(array, dir, i + 8, j + 9, k + 4, Blocks.air);
		setBlock(array, dir, i + 8, j + 10, k + 0, Blocks.air);
		setBlock(array, dir, i + 8, j + 10, k + 1, Blocks.air);
		setBlock(array, dir, i + 8, j + 10, k + 2, Blocks.air);
		setBlock(array, dir, i + 8, j + 10, k + 3, Blocks.air);
		setBlock(array, dir, i + 8, j + 10, k + 4, Blocks.air);
		setBlock(array, dir, i + 8, j + 11, k + 0, Blocks.air);
		setBlock(array, dir, i + 8, j + 11, k + 1, Blocks.air);
		setBlock(array, dir, i + 8, j + 11, k + 2, Blocks.air);
		setBlock(array, dir, i + 8, j + 11, k + 3, Blocks.air);
		setBlock(array, dir, i + 8, j + 11, k + 4, Blocks.air);
		setBlock(array, dir, i + 8, j + 12, k + 0, Blocks.air);
		setBlock(array, dir, i + 8, j + 12, k + 1, Blocks.air);
		setBlock(array, dir, i + 8, j + 12, k + 2, Blocks.air);
		setBlock(array, dir, i + 8, j + 12, k + 3, Blocks.air);
		setBlock(array, dir, i + 8, j + 12, k + 4, Blocks.air);/*
		setBlock(array, dir, i + 8, j + 13, k + 0, Blocks.air);
		setBlock(array, dir, i + 8, j + 13, k + 1, Blocks.air);
		setBlock(array, dir, i + 8, j + 13, k + 2, Blocks.air);
		setBlock(array, dir, i + 8, j + 13, k + 3, Blocks.air);
		setBlock(array, dir, i + 8, j + 13, k + 4, Blocks.air);*/
		setBlock(array, dir, i + 9, j + 0, k + 0, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 9, j + 0, k + 1, Blocks.air);
		setBlock(array, dir, i + 9, j + 0, k + 2, Blocks.air);
		setBlock(array, dir, i + 9, j + 0, k + 3, Blocks.air);
		setBlock(array, dir, i + 9, j + 0, k + 4, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 9, j + 1, k + 0, Blocks.air);
		setBlock(array, dir, i + 9, j + 1, k + 1, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 9, j + 1, k + 2, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 9, j + 1, k + 3, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 9, j + 1, k + 4, Blocks.air);
		setBlock(array, dir, i + 9, j + 2, k + 0, Blocks.air);
		setBlock(array, dir, i + 9, j + 2, k + 1, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 9, j + 2, k + 2, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 9, j + 2, k + 3, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 9, j + 2, k + 4, Blocks.air);
		setBlock(array, dir, i + 9, j + 3, k + 0, Blocks.air);
		setBlock(array, dir, i + 9, j + 3, k + 1, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 9, j + 3, k + 2, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 9, j + 3, k + 3, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 9, j + 3, k + 4, Blocks.air);
		setBlock(array, dir, i + 9, j + 4, k + 0, Blocks.air);
		setBlock(array, dir, i + 9, j + 4, k + 1, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 9, j + 4, k + 2, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 9, j + 4, k + 3, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 9, j + 4, k + 4, Blocks.air);
		setBlock(array, dir, i + 9, j + 5, k + 0, Blocks.air);
		setBlock(array, dir, i + 9, j + 5, k + 1, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 9, j + 5, k + 2, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 9, j + 5, k + 3, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 9, j + 5, k + 4, Blocks.air);
		setBlock(array, dir, i + 9, j + 6, k + 0, Blocks.air);
		setBlock(array, dir, i + 9, j + 6, k + 1, Blocks.air);
		setBlock(array, dir, i + 9, j + 6, k + 2, Blocks.air);
		setBlock(array, dir, i + 9, j + 6, k + 3, Blocks.air);
		setBlock(array, dir, i + 9, j + 6, k + 4, Blocks.air);
		setBlock(array, dir, i + 9, j + 7, k + 0, Blocks.air);
		setBlock(array, dir, i + 9, j + 7, k + 1, Blocks.air);
		setBlock(array, dir, i + 9, j + 7, k + 2, Blocks.air);
		setBlock(array, dir, i + 9, j + 7, k + 3, Blocks.air);
		setBlock(array, dir, i + 9, j + 7, k + 4, Blocks.air);
		setBlock(array, dir, i + 9, j + 8, k + 0, Blocks.air);
		setBlock(array, dir, i + 9, j + 8, k + 1, Blocks.air);
		setBlock(array, dir, i + 9, j + 8, k + 2, Blocks.air);
		setBlock(array, dir, i + 9, j + 8, k + 3, Blocks.air);
		setBlock(array, dir, i + 9, j + 8, k + 4, Blocks.air);
		setBlock(array, dir, i + 9, j + 9, k + 0, Blocks.air);
		setBlock(array, dir, i + 9, j + 9, k + 1, Blocks.air);
		setBlock(array, dir, i + 9, j + 9, k + 2, Blocks.air);
		setBlock(array, dir, i + 9, j + 9, k + 3, Blocks.air);
		setBlock(array, dir, i + 9, j + 9, k + 4, Blocks.air);
		setBlock(array, dir, i + 9, j + 10, k + 0, Blocks.air);
		setBlock(array, dir, i + 9, j + 10, k + 1, Blocks.air);
		setBlock(array, dir, i + 9, j + 10, k + 2, Blocks.air);
		setBlock(array, dir, i + 9, j + 10, k + 3, Blocks.air);
		setBlock(array, dir, i + 9, j + 10, k + 4, Blocks.air);
		setBlock(array, dir, i + 9, j + 11, k + 0, Blocks.air);
		setBlock(array, dir, i + 9, j + 11, k + 1, Blocks.air);
		setBlock(array, dir, i + 9, j + 11, k + 2, Blocks.air);
		setBlock(array, dir, i + 9, j + 11, k + 3, Blocks.air);
		setBlock(array, dir, i + 9, j + 11, k + 4, Blocks.air);
		setBlock(array, dir, i + 9, j + 12, k + 0, Blocks.air);
		setBlock(array, dir, i + 9, j + 12, k + 1, Blocks.air);
		setBlock(array, dir, i + 9, j + 12, k + 2, Blocks.air);
		setBlock(array, dir, i + 9, j + 12, k + 3, Blocks.air);
		setBlock(array, dir, i + 9, j + 12, k + 4, Blocks.air);/*
		setBlock(array, dir, i + 9, j + 13, k + 0, Blocks.air);
		setBlock(array, dir, i + 9, j + 13, k + 1, Blocks.air);
		setBlock(array, dir, i + 9, j + 13, k + 2, Blocks.air);
		setBlock(array, dir, i + 9, j + 13, k + 3, Blocks.air);
		setBlock(array, dir, i + 9, j + 13, k + 4, Blocks.air);*/
		setBlock(array, dir, i + 10, j + 0, k + 0, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 10, j + 0, k + 1, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 10, j + 0, k + 2, Blocks.air);
		setBlock(array, dir, i + 10, j + 0, k + 3, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 10, j + 0, k + 4, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 10, j + 1, k + 0, Blocks.air);
		setBlock(array, dir, i + 10, j + 1, k + 1, b, MinerBlocks.ORANGE.ordinal());

		setBlock(array, dir, i + 10, j + 1, k + 2, b, MinerBlocks.CONVEYOR.ordinal());
		setBlock(array, dir, i + 11, j + 1, k + 2, b, MinerBlocks.CONVEYOR.ordinal());
		setBlock(array, dir, i + 11, j + 1, k + 1, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 11, j + 1, k + 3, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 11, j + 2, k + 2, b, MinerBlocks.SILVER.ordinal());

		setBlock(array, dir, i + 10, j + 1, k + 3, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 10, j + 1, k + 4, Blocks.air);
		setBlock(array, dir, i + 10, j + 2, k + 0, Blocks.air);
		setBlock(array, dir, i + 10, j + 2, k + 1, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 10, j + 2, k + 2, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 10, j + 2, k + 3, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 10, j + 2, k + 4, Blocks.air);
		setBlock(array, dir, i + 10, j + 3, k + 0, Blocks.air);
		setBlock(array, dir, i + 10, j + 3, k + 1, Blocks.air);
		setBlock(array, dir, i + 10, j + 3, k + 2, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 10, j + 3, k + 3, Blocks.air);
		setBlock(array, dir, i + 10, j + 3, k + 4, Blocks.air);
		setBlock(array, dir, i + 10, j + 4, k + 0, Blocks.air);
		setBlock(array, dir, i + 10, j + 4, k + 1, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 10, j + 4, k + 2, b, MinerBlocks.SILVER.ordinal());
		setBlock(array, dir, i + 10, j + 4, k + 3, b, MinerBlocks.ORANGE.ordinal());
		setBlock(array, dir, i + 10, j + 4, k + 4, Blocks.air);
		setBlock(array, dir, i + 10, j + 5, k + 0, Blocks.air);
		setBlock(array, dir, i + 10, j + 5, k + 1, Blocks.air);
		setBlock(array, dir, i + 10, j + 5, k + 2, Blocks.air);
		setBlock(array, dir, i + 10, j + 5, k + 3, Blocks.air);
		setBlock(array, dir, i + 10, j + 5, k + 4, Blocks.air);
		setBlock(array, dir, i + 10, j + 6, k + 0, Blocks.air);
		setBlock(array, dir, i + 10, j + 6, k + 1, Blocks.air);
		setBlock(array, dir, i + 10, j + 6, k + 2, Blocks.air);
		setBlock(array, dir, i + 10, j + 6, k + 3, Blocks.air);
		setBlock(array, dir, i + 10, j + 6, k + 4, Blocks.air);
		setBlock(array, dir, i + 10, j + 7, k + 0, Blocks.air);
		setBlock(array, dir, i + 10, j + 7, k + 1, Blocks.air);
		setBlock(array, dir, i + 10, j + 7, k + 2, Blocks.air);
		setBlock(array, dir, i + 10, j + 7, k + 3, Blocks.air);
		setBlock(array, dir, i + 10, j + 7, k + 4, Blocks.air);
		setBlock(array, dir, i + 10, j + 8, k + 0, Blocks.air);
		setBlock(array, dir, i + 10, j + 8, k + 1, Blocks.air);
		setBlock(array, dir, i + 10, j + 8, k + 2, Blocks.air);
		setBlock(array, dir, i + 10, j + 8, k + 3, Blocks.air);
		setBlock(array, dir, i + 10, j + 8, k + 4, Blocks.air);
		setBlock(array, dir, i + 10, j + 9, k + 0, Blocks.air);
		setBlock(array, dir, i + 10, j + 9, k + 1, Blocks.air);
		setBlock(array, dir, i + 10, j + 9, k + 2, Blocks.air);
		setBlock(array, dir, i + 10, j + 9, k + 3, Blocks.air);
		setBlock(array, dir, i + 10, j + 9, k + 4, Blocks.air);
		setBlock(array, dir, i + 10, j + 10, k + 0, Blocks.air);
		setBlock(array, dir, i + 10, j + 10, k + 1, Blocks.air);
		setBlock(array, dir, i + 10, j + 10, k + 2, Blocks.air);
		setBlock(array, dir, i + 10, j + 10, k + 3, Blocks.air);
		setBlock(array, dir, i + 10, j + 10, k + 4, Blocks.air);
		setBlock(array, dir, i + 10, j + 11, k + 0, Blocks.air);
		setBlock(array, dir, i + 10, j + 11, k + 1, Blocks.air);
		setBlock(array, dir, i + 10, j + 11, k + 2, Blocks.air);
		setBlock(array, dir, i + 10, j + 11, k + 3, Blocks.air);
		setBlock(array, dir, i + 10, j + 11, k + 4, Blocks.air);
		setBlock(array, dir, i + 10, j + 12, k + 0, Blocks.air);
		setBlock(array, dir, i + 10, j + 12, k + 1, Blocks.air);
		setBlock(array, dir, i + 10, j + 12, k + 2, Blocks.air);
		setBlock(array, dir, i + 10, j + 12, k + 3, Blocks.air);
		setBlock(array, dir, i + 10, j + 12, k + 4, Blocks.air);/*
		setBlock(array, dir, i + 10, j + 13, k + 0, Blocks.air);
		setBlock(array, dir, i + 10, j + 13, k + 1, Blocks.air);
		setBlock(array, dir, i + 10, j + 13, k + 2, Blocks.air);
		setBlock(array, dir, i + 10, j + 13, k + 3, Blocks.air);
		setBlock(array, dir, i + 10, j + 13, k + 4, Blocks.air);*/
		setBlock(array, dir, i + 11, j + 0, k + 0, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 11, j + 0, k + 1, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 11, j + 0, k + 2, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 11, j + 0, k + 3, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 11, j + 0, k + 4, b, MinerBlocks.DARK.ordinal());
		setBlock(array, dir, i + 11, j + 1, k + 0, Blocks.air);
		setBlock(array, dir, i + 11, j + 1, k + 4, Blocks.air);
		setBlock(array, dir, i + 11, j + 2, k + 0, Blocks.air);
		setBlock(array, dir, i + 11, j + 2, k + 1, Blocks.air);
		setBlock(array, dir, i + 11, j + 2, k + 3, Blocks.air);
		setBlock(array, dir, i + 11, j + 2, k + 4, Blocks.air);
		setBlock(array, dir, i + 11, j + 3, k + 0, Blocks.air);
		setBlock(array, dir, i + 11, j + 3, k + 1, Blocks.air);
		setBlock(array, dir, i + 11, j + 3, k + 2, Blocks.air);
		setBlock(array, dir, i + 11, j + 3, k + 3, Blocks.air);
		setBlock(array, dir, i + 11, j + 3, k + 4, Blocks.air);
		setBlock(array, dir, i + 11, j + 4, k + 0, Blocks.air);
		setBlock(array, dir, i + 11, j + 4, k + 1, Blocks.air);
		setBlock(array, dir, i + 11, j + 4, k + 2, Blocks.air);
		setBlock(array, dir, i + 11, j + 4, k + 3, Blocks.air);
		setBlock(array, dir, i + 11, j + 4, k + 4, Blocks.air);
		setBlock(array, dir, i + 11, j + 5, k + 0, Blocks.air);
		setBlock(array, dir, i + 11, j + 5, k + 1, Blocks.air);
		setBlock(array, dir, i + 11, j + 5, k + 2, Blocks.air);
		setBlock(array, dir, i + 11, j + 5, k + 3, Blocks.air);
		setBlock(array, dir, i + 11, j + 5, k + 4, Blocks.air);
		setBlock(array, dir, i + 11, j + 6, k + 0, Blocks.air);
		setBlock(array, dir, i + 11, j + 6, k + 1, Blocks.air);
		setBlock(array, dir, i + 11, j + 6, k + 2, Blocks.air);
		setBlock(array, dir, i + 11, j + 6, k + 3, Blocks.air);
		setBlock(array, dir, i + 11, j + 6, k + 4, Blocks.air);
		setBlock(array, dir, i + 11, j + 7, k + 0, Blocks.air);
		setBlock(array, dir, i + 11, j + 7, k + 1, Blocks.air);
		setBlock(array, dir, i + 11, j + 7, k + 2, Blocks.air);
		setBlock(array, dir, i + 11, j + 7, k + 3, Blocks.air);
		setBlock(array, dir, i + 11, j + 7, k + 4, Blocks.air);
		setBlock(array, dir, i + 11, j + 8, k + 0, Blocks.air);
		setBlock(array, dir, i + 11, j + 8, k + 1, Blocks.air);
		setBlock(array, dir, i + 11, j + 8, k + 2, Blocks.air);
		setBlock(array, dir, i + 11, j + 8, k + 3, Blocks.air);
		setBlock(array, dir, i + 11, j + 8, k + 4, Blocks.air);
		setBlock(array, dir, i + 11, j + 9, k + 0, Blocks.air);
		setBlock(array, dir, i + 11, j + 9, k + 1, Blocks.air);
		setBlock(array, dir, i + 11, j + 9, k + 2, Blocks.air);
		setBlock(array, dir, i + 11, j + 9, k + 3, Blocks.air);
		setBlock(array, dir, i + 11, j + 9, k + 4, Blocks.air);
		setBlock(array, dir, i + 11, j + 10, k + 0, Blocks.air);
		setBlock(array, dir, i + 11, j + 10, k + 1, Blocks.air);
		setBlock(array, dir, i + 11, j + 10, k + 2, Blocks.air);
		setBlock(array, dir, i + 11, j + 10, k + 3, Blocks.air);
		setBlock(array, dir, i + 11, j + 10, k + 4, Blocks.air);
		setBlock(array, dir, i + 11, j + 11, k + 0, Blocks.air);
		setBlock(array, dir, i + 11, j + 11, k + 1, Blocks.air);
		setBlock(array, dir, i + 11, j + 11, k + 2, Blocks.air);
		setBlock(array, dir, i + 11, j + 11, k + 3, Blocks.air);
		setBlock(array, dir, i + 11, j + 11, k + 4, Blocks.air);
		setBlock(array, dir, i + 11, j + 12, k + 0, Blocks.air);
		setBlock(array, dir, i + 11, j + 12, k + 1, Blocks.air);
		setBlock(array, dir, i + 11, j + 12, k + 2, Blocks.air);
		setBlock(array, dir, i + 11, j + 12, k + 3, Blocks.air);
		setBlock(array, dir, i + 11, j + 12, k + 4, Blocks.air);/*
		setBlock(array, dir, i + 11, j + 13, k + 0, Blocks.air);
		setBlock(array, dir, i + 11, j + 13, k + 1, Blocks.air);
		setBlock(array, dir, i + 11, j + 13, k + 2, Blocks.air);
		setBlock(array, dir, i + 11, j + 13, k + 3, Blocks.air);
		setBlock(array, dir, i + 11, j + 13, k + 4, Blocks.air);*/

		return array;
	}

}
